networks:
  proxy-tier:
    external:
      name: fs-proxy
services:
  freescout-app:
    container_name: freescout-app
    environment:
      - VIRTUAL_HOST=servicedesk.cjwebster.net
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=servicedesk.cjwebster.net
      - LETSENCRYPT_EMAIL=craigwebster14@gmail.com
      - CONTAINER_NAME=freescout-app
      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - SITE_URL=https://servicedesk.cjwebster.net
      - ADMIN_EMAIL=craigwebster14@gmail.com
      - ADMIN_PASS=BillyBob2010
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
      - TIMEZONE=Europe/London
    image: tiredofit/freescout
    links:
      - freescout-db
    networks:
      - proxy-tier
    ports:
      - '9080:80'
    restart: always
    volumes:
          ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
      - fs_data:/data
          ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
      - fs_logs:/www/logs
  freescout-db:
    container_name: freescout-db
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - CONTAINER_NAME=freescout-db
    image: tiredofit/mariadb
    networks:
      - proxy-tier
    restart: always
    volumes:
      - fs_db:/var/lib/mysql
  freescout-db-backup:
    container_name: freescout-db-backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    image: tiredofit/db-backup
    links:
      - freescout-db
    networks:
      - proxy-tier
    restart: always
    volumes:
      - fs_dbbackup:/backup
version: '2'
volumes:
  fs_data:
    external: true
  fs_db:
    external: true
  fs_dbbackup:
    external: true
  fs_logs:
    external: true