services:
  snipeit:
    image: snipe/snipe-it:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
    - "8090:80"
    volumes:
    - logs:/var/www/html/storage/logs
    depends_on:
    - mariadb
    - redis
    env_file:
    #- .env.docker
    - stack.env
    networks:
    - snipeit-backend

  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
    - snipeit_db:/var/lib/mysql
    env_file:
    #- .env.docker
    - stack.env
    networks:
    - snipeit-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend


volumes:
  snipeit_db:
  logs:

networks:
  snipeit-backend: {}